[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "forge-std/=lib/forge-std/src/"
]

# Optimizer settings
optimizer = true
optimizer_runs = 200
via_ir = true

# Gas reporting
gas_reports = ["*"]

# Ethereum settings
evm_version = "shanghai"
solc_version = "0.8.24"

# Testing
verbosity = 3
ffi = false
ast = true
build_info = true

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

[doc]
out = "docs"
title = "PassMint Smart Contracts"